### ISSUE TITLE
A typographical error in the README?

### ISSUE THREAD

**Issue by shiwangyan** [hwanhuh/2D-GS-Viser-Viewer#1]
I couldn't find '_message_api.py' in viser.
I find 'def cast_vector(vector: TVector | onp.ndarray, length: int) -> TVector:' in '_scene_api.py'.
Do you acctually mean '_scene_api.py'?

**Comment by hwanhuh** [comment]
what is your viser version & os?  
Mine is latest on Ubuntu 20.04

**Comment by shiwangyan** [comment]
my  viser version is 0.2.0 and os is windows

**Comment by hwanhuh** [comment]
umm
It looks like a function with the same function.
can you try changing it and let me know if it works?

**Comment by shiwangyan** [comment]
I gave it a try and it ran successfully, but when I opened the website, it was just a blank page.
Then, I switched Viser back to version 0.1.34, fix the code of '_message_api.py' , and encountered the same issue—a blank page still.
![image](https://github.com/hwanhuh/2D-GS-Viser-Viewer/assets/60057517/a3ab32f5-ab1b-42aa-ac48-0e453ed2a825)

![image](https://github.com/hwanhuh/2D-GS-Viser-Viewer/assets/60057517/d47c6dd0-6c8d-4a95-92f7-622e88477070)

**Comment by shiwangyan** [comment]
So I'm not sure weather it works.
By the way, there seems to be an issue with the fix code indentation.
```python 
    def cast_vector(vector: TVector | onp.ndarray, length: int) -> TVector:
        if isinstance(vector, tuple): return cast(TVector, vector)
        else:
            if vector.__class__.__name__ == 'RollPitchYaw':
                x = vector.roll 
                y = vector.pitch 
                z = vector.yaw
                return cast(TVector, (x, y, z))
            else:
                vector = tuple(vector)
                return cast(TVector, vector)
```

**Comment by hwanhuh** [comment]
Thanks for sharing. 
I will check more accurate version and dependency issues. 
And can you share the ply file you used? I'll try opening it on my own too.

**Comment by shiwangyan** [comment]
Yes, but It's too big to upload.
And I don't have a google drive...

**Comment by hwanhuh** [comment]
Ah... if you can send it to me by email, I'll try to open it. 
If the full iter file is too large, you can just send the 7000 iter file.

**Comment by shiwangyan** [comment]
The 7000 iter file is even larger...
I'll send it to you via email instead.
May I have your email address, please?

**Comment by hwanhuh** [comment]
Please send it to ‘gjghks950@gmail.com’ or 'gjghks950@naver.com' :)

**Comment by shiwangyan** [comment]
Maybe the issue is related to the browser?
For example, something like WebGPU and WebGL？
They are not supported by my browser.

**Comment by hwanhuh** [comment]
If your browser does not support WebGPU or WebGL, it will not be able to use Viser effectively.

- three.js via react-three-fiber and drei: These libraries are built on top of WebGL (and in some cases, WebGPU) to render 3D graphics in the browser. Without WebGL or WebGPU support, three.js cannot function; thus, any 3D rendering done by Viser would fail.

- React and Vite / Rollup: While these tools are responsible for building and bundling the web client, they rely on the underlying capabilities of the browser to render content.

Hence, without WebGL or WebGPU support, Viser's functionality will be significantly limited. 

Additionally, with my current version of Viser: 0.1.32 (sorry for the versioning), your scene successfully loaded on my device, as shown below:
![image](https://github.com/hwanhuh/2D-GS-Viser-Viewer/assets/19833216/1a7bd65d-b3cb-401b-86f4-b11b18b7f7e0)

Regarding the WebGPU issue, it is crucial to ensure your browser supports these technologies for Viser to function correctly.

**Comment by shiwangyan** [comment]
It appears the issue was with the Edge browser. After switching to Chrome, everything is working fine now.

**Comment by hwanhuh** [comment]
I'm glad switching to Chrome resolved the issue! :)
