### ISSUE TITLE
gaussian disk viewer

### ISSUE THREAD

**Issue by Rso0902** [hwanhuh/2D-GS-Viser-Viewer#10]
Thank you for providing this tool. May I ask if it is possible to visualize a Gaussian elliptical disk?

**Comment by hwanhuh** [comment]
Currently, the viewer does not support visualizing elliptical disks. 
I'd like to include that feature in a later update. :)

**Comment by hwanhuh** [comment]
![image](https://github.com/hwanhuh/2D-GS-Viser-Viewer/assets/19833216/be04d38a-54e0-4069-8e86-3a7d1c3c252e)

Is this what you expect?
