### ISSUE TITLE
2D disk looks different from the image on the paper.

### ISSUE THREAD

**Issue by cdfan0627** [hwanhuh/2D-GS-Viser-Viewer#15]
Thanks for sharing the viewer. I’m wondering why the 2D disk looks different from the image in the paper.

**Comment by hwanhuh** [comment]
You can modify the kernel function used to visualize a 2D Disk. 
Currently, the kernel is defined as follows.

```python 
torch.exp(-1/2 * 100 * torch.clamp(opacity-0.5, min=0) ** 2)
```

I don't know what specific kernel design is used for the paper's disk visualization.

**Comment by RealQingyue** [comment]
See https://github.com/hbb1/2d-gaussian-splatting/issues/115

**Comment by hbb1** [comment]
We should modify the kernel function of 2D Gaussian.
https://github.com/hbb1/diff-surfel-rasterization/blob/28c928a36ea19407cd9754d068bd9a9535216979/cuda_rasterizer/forward.cu#L365-L366

```C++
float rho = min(rho3d, rho2d);
rho = 100 * max(rho-0.5, 0)
```

Unfortunately, this requires modifying the Cuda code so that a surfel within a radius is fully opaque.
