### ISSUE TITLE
ModuleNotFoundError: No module named 'arguments'

### ISSUE THREAD

**Issue by shiwangyan** [hwanhuh/2D-GS-Viser-Viewer#2]
error message：
D:\2DGS\2d-gaussian-splatting>python .\2D-GS-Viser-Viewer\viewer.py -m data/output
Traceback (most recent call last):
  File "D:\2DGS\2d-gaussian-splatting\2D-GS-Viser-Viewer\viewer.py", line 16, in <module>
    from arguments import ModelParams, PipelineParams, get_combined_args
ModuleNotFoundError: No module named 'arguments'
![image](https://github.com/hwanhuh/2D-GS-Viser-Viewer/assets/60057517/8d863482-10f2-473f-aa4e-4fb8809f31c9)

**Comment by hwanhuh** [comment]
My installation guide is a little bit confused.
Do not make individual folders of viewer, just dirsctly paste it to the 2D GS folders. 
i.e., viewer.py should locate;: ~/2d-gaussian-splatting/viewer.py

**Comment by shiwangyan** [comment]
ok
