### ISSUE TITLE
Why do I use pyinstaller to package viewer.py. The exe I get won't run?

### ISSUE THREAD

**Issue by chenqi13814529300** [hwanhuh/2D-GS-Viser-Viewer#6]

**Comment by chenqi13814529300** [comment]
![image](https://github.com/hwanhuh/2D-GS-Viser-Viewer/assets/59059403/f6e49ed7-50e5-4c7a-b525-fe6e98586f33)

**Comment by hwanhuh** [comment]
I haven't test to package viewer as an window executable file using pyinstaller. 
I recommend you to use the viewer as its published

**Comment by chenqi13814529300** [comment]
The posted viewer internet speed is too slow for smooth browsing, are there some other options.

**Comment by hwanhuh** [comment]
If you have your custom CUDA available GPU, launching the viewer in your local is the best.

**Comment by chenqi13814529300** [comment]
Thanks, I hope you guys make more progress on the 2D Gaussian viewer. It's not very easy to operate at the moment, I hope it can be operated with a mouse.

**Comment by hwanhuh** [comment]
The viewer supports moving the view by clicking with the mouse or zooming in and out with the wheel.
